//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        public int id { get; set; }
        public string Name { get; set; }
        public int Cost { get; set; }
        public string Seria { get; set; }
        public Nullable<int> id_Service { get; set; }
    
        public virtual serivce serivce { get; set; }
    }
}
